import{a as y,S as b,i as d}from"./assets/vendor-851Qsuw-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const L="48548888-6a688bae8a9a8d1a3f9b35105",w="https://pixabay.com/api/";async function v(t,s=1,i=15){try{return(await y.get(w,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:i,page:s}})).data}catch(o){throw console.error("Error fetching images:",o),o}}function E(t){return t.map(({webformatURL:s,largeImageURL:i,tags:o,likes:e,views:r,comments:a,downloads:g})=>`
          <div class="photo-card">
            <a href="${i}" class="gallery-link">
              <img src="${s}" alt="${o}" loading="lazy" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${e}</p>
              <p><b>Views:</b> ${r}</p>
              <p><b>Comments:</b> ${a}</p>
              <p><b>Downloads:</b> ${g}</p>
            </div>
          </div>`).join("")}const S=document.querySelector("#search-form"),f=document.querySelector(".gallery"),n=document.querySelector(".load-more"),l=document.createElement("div");l.classList.add("loader");document.body.appendChild(l);let u="",c=1;const p=15;let P=new b(".gallery a");S.addEventListener("submit",async t=>{t.preventDefault(),u=t.target.searchQuery.value.trim(),u&&(c=1,f.innerHTML="",n.classList.add("hidden"),await m())});n.addEventListener("click",async()=>{c+=1,await m()});async function m(){try{q();const t=await v(u,c,p);if(h(),t.hits.length===0){d.error({title:"Error",message:"No images found for your query. Please try a different search.",position:"topRight"});return}f.insertAdjacentHTML("beforeend",E(t.hits)),P.refresh(),$(),c*p>=t.totalHits?(n.classList.add("hidden"),d.info({title:"End of results",message:"You have reached the end of the image search results.",position:"topRight"})):n.classList.remove("hidden")}catch{h(),d.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}}function q(){l.style.display="block"}function h(){l.style.display="none"}function $(){const{height:t}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
